### PR TITLE
Fix the config file

### LINKED ISSUE #69: config.jl bug
https://github.com/JuliaComputing/ArrayFire.jl/blob/master/src/config.jl#L8 
should be pulled out

### PR DESCRIPTION
**Pull request by ranjanan**
Fixes bug in config file. Fixes #69.

### CODE REVIEW

File: src/config.jl [hunk 1]
```diff
@@ -3,9 +3,11 @@ let
...
-        Libdl.dlopen(lib)
-        succeeded = true
-        succeeded || error("ArrayFire library not found")
+        try
+            Libdl.dlopen(lib)
+            succeeded = true
+        end
         @eval const af_lib = $lib
     end
+    succeeded || error("ArrayFire library not found")
```
Comment (ViralBShah) [inline src/config.jl]: Why not just have this in a `catch` block with the succeeded business?

Comment (ranjanan) [inline src/config.jl]: Sure, we don't need the `succeeded` variable then.
